--INSERT INTO item (name, price, taxRate, priceWithTax, vendor)
--VALUES
--	('iPhone 7 Plus', 10000, 10, 11000, 'Apple'),
--	('扇風機', 5000, 10, 5500, 'クーラー会社'),
--	('カップ麺', 300, 8, 324, '月製');
	
-- 商品名マスタのデータ
INSERT INTO masterItemName (name)
VALUES
	('iPhone'),
	('iPhone 3G'),
	('iPhone 3GS'),
	('iPhone 4'),
	('iPhone 4S'),
	('iPhone 5'),
	('iPhone 5c'),
	('iPhone 5s'),
	('iPhone 6'),
	('iPhone 6 Plus'),
	('iPhone 6s'),
	('iPhone 6s Plus'),
	('iPhone SE'),
	('iPhone 7'),
	('iPhone 7 Plus'),
	('iPhone 8'),
	('iPhone 8 Plus'),
	('iPhone X'),
	('iPhone XS'),
	('iPhone XS XS Max'),
	('iPhone XR'),
	('iPhone 11 Pro'),
	('iPhone 11 Pro Max'),
	('iPhone 11'),
	('iPhone SE2'),
	('iPhone 12 Pro'),
	('iPhone 12 Pro Max'),
	('iPhone 12'),
	('iPhone 12 mini'),
	('iPhone 13 Pro'),
	('iPhone 13 Pro Max'),
	('iPhone 13'),
	('iPhone 13 mini'),
	('iPhone SE3'),
	('iPhone 14 Pro'),
	('iPhone 14 Pro Max'),
	('iPhone 14'),
	('iPhone 14 Plus'),
	('ゆずの素'),
	('ゆずマン'),
	('ゆず一家'),
	('ゆずえん'),
	('ゆずマンの夏'),
	('トビラ'),
	('ユズモア'),
	('すみれ'),
	('ゆずスマイル'),
	('１'),
	('Home [1997 - 2000]'),
	('Going [2001 - 2005]'),
	('リボン'),
	('ゆずのね [1997 - 2007]'),
	('WONDERFUL WORLD'),
	('FURUSATO'),
	('2 -Ni-'),
	('LAND'),
	('新世界'),
	('TOWA'),
	('ゆずイロハ [1997 - 2017]'),
	('BIG YELL'),
	('YUZUTOWN'),
	('PEOPLE'),
	('SEES'),
	('アクエリアス 280mlPET'),
	('アクエリアス 500mlPET'),
	('アクエリアス 1000mlPET'),
	('アクエリアス 2LPET'),
	('アクエリアス 1日分のマルチビタミン 500mlPET'),
	('アクエリアス 1日分のマルチビタミン 2LPET'),
	('アクエリアス ゼロ 500mlPET'),
	('アクエリアス ゼロ 2000mlPET'),
	('コカ・コーラ 300mlPET'),
	('コカ・コーラ 350mlPET'),
	('コカ・コーラ 500mlPET'),
	('コカ・コーラ 1000mlPET'),
	('コカ・コーラ 1500mlPET'),
	('ファンタ オレンジ 350mlPET'),
	('ファンタ オレンジ 500mlPET'),
	('ファンタ オレンジ 1500mlPET'),
	('ファンタ グレープ 350mlPET'),
	('ファンタ グレープ 500mlPET'),
	('ファンタ グレープ 1500mlPET'),
	('い･ろ･は･す プラズマ乳酸菌 免疫ケア りんごとほんのりヨーグルト味 540ml'),
	('い･ろ･は･す 天然水 ラベルレス 540mlPET'),
	('い･ろ･は･す シャインマスカット 540mlPET'),
	('い･ろ･は･す ハスカップ 540mlPET'),
	('い･ろ･は･す なし 540mlPET'),
	('い･ろ･は･す みかん 540mlPET'),
	('い･ろ･は･す もも 540mlPET'),
	('い･ろ･は･す 天然水（北海道） 540mlPET'),
	('い･ろ･は･す 天然水（北海道） 540mlPET'),
	('い･ろ･は･す 天然水 ラベルレス 2LPET'),
	('い･ろ･は･す 天然水 1020mlPET'),
	('い･ろ･は･す 北海道の天然水 285mlPET'),
	('い･ろ･は･す 天然水（北海道） 2LPET'),
	('い･ろ･は･す スパークリングれもん 515mlPET');
	
-- ベンダーマスタのデータ
INSERT INTO masterVendor (name)
VALUES
	('Apple'),
	('株式会社セーニャ'),
	('コカ・コーラ　カスタマーマーケティング');
	
	
